allowBuilds:
  esbuild: true
  sharp: false
minimumReleaseAgeExclude:
  - astro@6.4.7
overrides:
  astro@<6.1.10: '>=6.1.10'
  astro@<6.1.6: '>=6.1.6'
  defu@<=6.1.4: '>=6.1.5'
  devalue@<5.6.4: '>=5.6.4'
  devalue@<=5.6.3: '>=5.6.4'
  esbuild@>=0.17.0 <0.28.1: '>=0.28.1'
  esbuild@>=0.27.3 <0.28.1: '>=0.28.1'
  h3@<1.15.9: '>=1.15.9'
  h3@<=1.15.8: '>=1.15.9'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  smol-toml@<1.6.1: '>=1.6.1'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
